sudo: required
dist: trusty
group: edge

language: java

jdk: oraclejdk8

services: docker

notifications:
    email: testifybot@gmail.com
    on-success: change
    on-failure: always

cache:
    apt: true
    pip: true
    directories: $HOME/.m2

addons:
    apt:
        packages:
         - gnupg
         - net-tools
            
env:
  global:
     - MAVEN_OPTS="-client -Xms512m -Xmx2048m"
  matrix:
    - DOCKER_VERSION=1.11.2
    - DOCKER_VERSION=1.12.6
    - DOCKER_VERSION=1.13.1
    - DOCKER_VERSION=17.06.0~ce

before_install: ./before_install.sh

script: ./script.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - ./after_success.sh
    
